export const EMOTION_KEYWORDS = [
    'calm',
    'relaxing',
    'relax',
    'soft',
    'emotional',
    'happy',
    'sad',
    'dark',
    'bright',
    'chill',
    'peaceful',
    'inspiring',
    'inspiration',
    'romantic',
    'focus',
    'joyful',
    'angry',
    'excited',
    'hopeful',
    'mellow',
    'serene',
    'nostalgic',
    'intense',
    'melancholy',
    'uplifting',
    'playful',
    'romantic',
    'motivated',
    'calming',
    'peaceful',
    'comforting',
    'euphoric',
    'gloomy',
    'suspenseful',
    'dreamy',
    'reflective',
    'content',
    'tension',
    'optimistic',
    'lonely',
    'vibrant',
    'thoughtful',
    'nostalgic',
    'surreal',
    'bitter',
    'elated'
];


export const TAG_KEYWORDS = [
    // Chủ đề thiên nhiên
    'nature',
    'forest',
    'rain',
    'water',
    'ocean',
    'mountain',
    'sky',
    'sunset',
    'sunrise',
    'night',
    'storm',
    'river',
    'snow',
    'fire',
    'wind',

    // Thể loại / phong cách
    'ambient',
    'lofi',
    'cinematic',
    'epic',
    'classical',
    'electronic',
    'piano',
    'guitar',
    'acoustic',
    'synth',
    'orchestra',
    'beats',
    'instrumental',

    // Hoạt động
    'study',
    'focus',
    'sleep',
    'meditation',
    'workout',
    'relax',
    'gaming',
    'reading',
    'yoga',
    'work',

    // Concept & vibe
    'dreamy',
    'fantasy',
    'sci-fi',
    'cosmic',
    'space',
    'vintage',
    'retro',
    'minimal',
    'abstract',
    'aesthetic',

    // Màu sắc (phù hợp background)
    'dark',
    'light',
    'blue',
    'red',
    'green',
    'purple',
    'pink',
    'gold',
    'black',
    'white',

    // Mood thêm bổ sung
    'happy',
    'sad',
    'calm',
    'soft',
    'chill',
    'bright',
    'moody',
    'peaceful',
    'inspiring',
    'romantic',

    // Bối cảnh
    'city',
    'urban',
    'street',
    'landscape',
    'nature',
    'forest',
    'cyberpunk',
    'neon',
    'space',
    'ocean',

    // Level / tone
    'high-energy',
    'low-energy',
    'slow',
    'fast',
    'smooth',
    'deep',

    // Khác
    'background',
    'mood',
    'vibes',
    'ambient-sound',
    'soundscape'
];
